# Generated by Django 5.2.1 on 2025-05-21 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='num_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
